version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Node version:"
      - node -v
      - echo "npm version:"
      - npm -v

  pre_build:
    commands:
      - echo "Pre-build started on $(date)"
      - cd frontend
      - npm install

  build:
    commands:
      - echo "Running Frontend Tests..."
      # CI=true 설정은 테스트가 Watch 모드로 대기하지 않고, 한 번 실행 후 종료되게 합니다.
      - export CI=true
      # package.json에 test 스크립트가 있을 때만 실행합니다.
      - npm run test --if-present