version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Node version:"
      - node -v
      - echo "npm version:"
      - npm -v
      
  pre_build:
    commands:
      - echo "Pre-build started on $(date)"
      - cd frontend
      - npm install
      
  build:
    commands:
      - echo "Building React application..."
      # 빌드 시 필요한 환경 변수 설정
      - export VITE_API_URL="http://team0203-backend-alb-1875315160.us-east-1.elb.amazonaws.com"
      - echo "API URL $VITE_API_URL"
      - npm run build
      - cd ..
      
  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - 'frontend/dist/**/*'
    - 'frontend/nginx.conf'
    - 'frontend/scripts/**/*'
    - 'frontend/appspec.yml'
  discard-paths: no

cache:
  paths:
    - 'frontend/node_modules/**/*'