version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node version:"
      - node -v
      - echo "npm version:"
      - npm -v
      
  pre_build:
    commands:
      - echo "Pre-build started on $(date)"
      - echo "Current directory:"
      - pwd
      - echo "Installing dependencies..."
      - cd frontend
      - npm ci
      
  build:
    commands:
      - echo "Building React application..."
      - export VITE_API_URL="team0203-backend-alb-1875315160.us-east-1.elb.amazonaws.com"
      - echo "API URL: $VITE_API_URL"
      - npm run build
      - echo "Build artifacts:"
      - ls -la dist/
      - cd ..
      
  post_build:
    commands:
      - echo "Build completed on $(date)"
      - ls -la frontend/dist/

artifacts:
  files:
    - 'frontend/dist/**/*'
    - 'frontend/nginx.conf'
    - 'frontend/scripts/**/*'
    - 'frontend/appspec.yml'
  name: FrontendArtifact
  
cache:
  paths:
    - 'frontend/node_modules/**/*'