version: 0.0
os: linux

files:
  - source: build/libs/
    destination: /home/ec2-user/app

  - source: scripts/
    destination: /home/ec2-user/scripts

# [수정] 기존 파일이 있을 경우 덮어쓰도록 설정 추가
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

  - object: /home/ec2-user/scripts
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ec2-user

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root # 폴더 생성 및 소유권 변경을 위해 root 사용

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
      
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user